Turn host.session into a property
SatelliteQE/broker pull request #103
Opened 2021-04-26 12:31 UTC by mshriver

If connect wasn't called, session can be referenced when it was None.

2021-06-16 12:11 UTC, JacobCallahan requested changes
Can you use close in getstate? That is cleaner than the current implementation

2021-06-17 18:08 UTC, JacobCallahan commented
With session becoming a property, we no longer need to call or check for `connect` in the host, context managers, and other places relating to host construction.
Would you mind removing those pieces as part of this PR as well?

2021-06-17 18:18 UTC, mshriver commented
@JacobCallahan Absolutely, wanted to hear some buy-in on changing the pattern here for the session handling first. Likely a few small changes that could happen in robottelo as well.

2021-06-17 18:26 UTC, JacobCallahan commented
@mshriver absolutely! Turning this into a property is going to be VERY nice!

2021-06-17 18:29 UTC, mshriver commented on broker/hosts.py
> +        self.password = kwargs.get("password", settings.HOST_PASSWORD)
Note the typo that was here is getting fixed.

2021-06-17 20:54 UTC, JacobCallahan commented on broker/hosts.py
> +        self.password = kwargs.get("password", settings.HOST_PASSWORD)
hahaha nice!!

2021-06-17 20:58 UTC, JacobCallahan approved these changes

2021-06-17 20:58 UTC, merged