Adding error message when no flags are specified
SatelliteQE/broker pull request #108
Opened 2021-05-24 14:39 UTC by Griffin-Sullivan

Added an error message: "Could not determine an appropriate provider" when the user does not specify options to certain commands. Ex: `broker execute` or `broker checkout` with no workflow or nick.

2021-05-24 14:40 UTC, Griffin-Sullivan commented
Just realized I did not test this enough. Going to update the commit with a fix.

2021-05-24 15:11 UTC, Griffin-Sullivan commented
Ok from what I tested, this should work. Also, I'm not sure what I did to make my commits so weird, so if someone could help resolve that, it would be much appreciated.

2021-05-24 17:09 UTC, JacobCallahan requested changes

2021-05-24 17:09 UTC, JacobCallahan commented on broker/broker.py
> +            logger.error("Could not determine an appropriate provider")
We can simplify further!
```suggestion
        for key, action in PROVIDER_ACTIONS.items():
            if key in kwargs:
                self._provider_actions[key] = action
        if not self._provider_actions:
            logger.error("Could not determine an appropriate provider")
```

2021-05-26 12:39 UTC, Griffin-Sullivan commented on broker/broker.py
> +            logger.error("Could not determine an appropriate provider")
Oh I see. I didn't think to check that `_provider_actions` was null that way.

2021-05-26 14:27 UTC, JacobCallahan approved these changes

2021-05-27 14:26 UTC, merged