Added the ability to store important output from cli
SatelliteQE/broker pull request #109
Opened 2021-05-27 17:36 UTC by JacobCallahan

Added Emitter class and emit instance to helpers
Added a way to gain failure information for AnsibleTower

2021-05-27 17:37 UTC, JacobCallahan commented
@rplevka can you check this out locally and see if it meets your needs? I can make adjustments as needed.

Also, if anyone else would like other important information emitted, please let me know.

2021-05-28 13:44 UTC, tstrych approved these changes
LGTM. Approving in front, but should be further discussed with @rplevka as Jake mentioned.

2021-05-28 13:44 UTC, tstrych commented on README.md
> +If running in a CI or other automated environment, Broker offers the choice to store important output information in an output file. This is json-formatted data. Please be aware that any existing fil
can you be more specific what is important output information ?
when I read this I don't know what values I can expect inside the json file.

2021-05-28 13:44 UTC, tstrych commented on tests/test_helpers.py
> +    assert written == {"test": "value", "another": 5, "thing": 13}
I really appreciate that you wrote a test on these. Maybe I would also mock a bit more real data, just to see it on something more real and more complex. 
Of course not required change for emit v1 :+1:

2021-05-28 13:44 UTC, tstrych commented on broker/helpers.py
> +            kwargs.update(arg)
I don't understand the purpose of this line: `kwargs.update(arg)`
Would you mind explain it to me ?

2021-05-28 20:02 UTC, JacobCallahan commented on README.md
> +If running in a CI or other automated environment, Broker offers the choice to store important output information in an output file. This is json-formatted data. Please be aware that any existing fil
I could flesh out the description a little if this PR needs other updates

2021-05-28 20:04 UTC, JacobCallahan commented on tests/test_helpers.py
> +    assert written == {"test": "value", "another": 5, "thing": 13}
More complex tests are always welcome in future PRs :)

2021-05-28 20:06 UTC, JacobCallahan commented on broker/helpers.py
> +            kwargs.update(arg)
Sure thing! So the emitter accepts both keyword-based arguments as well as positional arguments.
In this loop, we're going over a list of possible positional arguments, which can only be dictionaries.
We then update the keyword arguments dictionary with each of the positional dictionaries passed in.
This allows us to just track one object that will be used to update the existing data.

2021-06-10 15:26 UTC, rplevka commented
We tried this with @ogajduse 
and any commands returns the same error instantly:
```
$ broker --help
[ERROR 210610 17:24:46] BrokerError: expected str, bytes or os.PathLike object, not NoneType
```

2021-06-10 21:51 UTC, rplevka commented
so I tried to run a simple workflow - `list-templates` and broker crashed as `WorkflowJob`  seemed not being json-serializable:

```
Traceback (most recent call last):
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/commands.py", line 18, in __call__
    return self.main(*args, **kwargs)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/commands.py", line 372, in execute
    helpers.emit({"output": result})
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/helpers.py", line 287, in __call__
    return self.emit_to_file(*args, **kwargs)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/helpers.py", line 284, in emit_to_file
    self.file.write_text(json.dumps(curr_data, indent=4, sort_keys=True))
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/awxkit/api/mixins/has_create.py", line 186, in _filter_ds_from_payload
    return dumps(filtered, *a, **kw)
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WorkflowJob is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rplevka/.virtualenvs/broker_jake/bin/broker", line 8, in <module>
    sys.exit(cli())
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/commands.py", line 22, in __call__
    helpers.emit(return_code=err.error_code, error_message=err.message)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/helpers.py", line 287, in __call__
    return self.emit_to_file(*args, **kwargs)
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/broker/helpers.py", line 284, in emit_to_file
    self.file.write_text(json.dumps(curr_data, indent=4, sort_keys=True))
  File "/home/rplevka/.virtualenvs/broker_jake/lib/python3.9/site-packages/awxkit/api/mixins/has_create.py", line 186, in _filter_ds_from_payload
    return dumps(filtered, *a, **kw)
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable

```

2021-06-14 10:55 UTC, ogajduse reviewed
Good job @JacobCallahan!
I have a few comments to add.

I am completely satisfied with the JSON produced in case of success. We can not wish to display/output more than it provides. 
To the output produced in case of failure that is listed below: The job URLs listed in there are pointing to AT WebUI. I would like the JSON to also contain links to AT API so we would have a direct API link for the subsequent machine processing without the need for any API URL compilation.

```json
{
  "Reason(s)": {
    "job": "satlab-tower-deploy-base-rhel-from-rhvm-02",
    "reason": "No result was found for the passed string, or the string passed not found",
    "task": "Deploying a RHEL Template on RHVM"
  },
  "URL": "https://our.at.com/#/workflows/638255",
  "Workflow Status:": "failed",
  "action": "execute",
  "arguments": {
    "rhel_version": "7",
    "workflow": "deploy-base-rhel"
  },
  "auth_type": "token",
  "hosts": [],
  "job_url": "https://our.at.com/#/workflows/638255",
  "provider": "AnsibleTower"
}
```

I assume the implementation would like similar to this:
https://github.com/SatelliteQE/broker/blob/f6a5fc4c989f60e3c3f4af1dacfc132e65790b88/broker/providers/ansible_tower.py#L377-L381

The JSON output of the failed runs does not include `output`. Is it possible to include it? I see it as an extra Tower API call to `/api/v2/workflow_jobs/<jobid>/`. This will not add too much time, will it?

2021-06-14 10:55 UTC, ogajduse commented on broker/providers/ansible_tower.py
> +                f"{subject.capitalize()} Status:": job.status,
Can we get rid of the colon here? It does not look nice in the JSON output. But this is just more a cosmetic thing.
```json
{
   "Workflow Status:": "failed",
}
```

2021-06-14 11:10 UTC, rplevka requested changes
@JacobCallahan thanks for the implementation!
I definitely like the structure of the JSON, and I agree with @ogajduse that it could contain API urls in case of a failure.


ACK pending @ogajduse comments.

2021-06-14 16:01 UTC, mshriver commented on broker/hosts.py
> +    def __getstate__(self):
Nice!

2021-06-14 16:01 UTC, mshriver approved these changes

2021-06-14 18:15 UTC, merged