Realize non-default port guest connect on broker
SatelliteQE/broker pull request #154
Opened 2022-05-27 07:12 UTC by yanpliu

Realize the non-default port 22 guest connect on broker.

Cases PASS for default port 22 log on and non-default guest connect by command.

2022-05-27 08:33 UTC, jyejare requested changes
ACK pending comments !

2022-05-27 08:33 UTC, jyejare commented on broker/session.py
> +        port = kwargs.get("port", "port") or 22
```suggestion
        port = kwargs.get("port", 22)
```

2022-05-27 08:33 UTC, jyejare commented on broker/session.py
> +        simple_retry(sock.connect, [(host, kwargs.get("port", port))])
```suggestion
        simple_retry(sock.connect, [(host, port)])
```

2022-05-27 11:46 UTC, JacobCallahan requested changes
Please use `HOST_SSH_PORT`as the settings name (clarity) and add it to the example settings file.
Thanks for contributing to Broker!

2022-05-27 11:46 UTC, JacobCallahan commented on broker/settings.py
> +    Validator("PORT", default=22),
```suggestion
    Validator("HOST_SSH_PORT", default=22),
```

2022-05-27 11:46 UTC, JacobCallahan commented on broker/hosts.py
> +        self.port = kwargs.get("port", settings.PORT)
```suggestion
        self.port = kwargs.get("port", settings.HOST_SSH_PORT)
```

2022-05-31 05:39 UTC, yanpliu commented on broker/session.py
> +        port = kwargs.get("port", "port") or 22
> 
@jyejare 
Thanks for your suggestion, have already updated.

2022-05-31 05:39 UTC, yanpliu commented on broker/session.py
> +        simple_retry(sock.connect, [(host, kwargs.get("port", port))])
> 
@jyejare 
Thanks for your suggestion, have already updated.

2022-05-31 05:40 UTC, yanpliu commented on broker/settings.py
> +    Validator("PORT", default=22),
> 
@JacobCallahan 
Thanks for your suggestion, have already updated.

2022-05-31 05:40 UTC, yanpliu commented on broker/hosts.py
> +        self.port = kwargs.get("port", settings.PORT)
> 
@JacobCallahan 
Thanks for your suggestion, have already updated.

2022-05-31 05:47 UTC, yanpliu commented
@JacobCallahan  @jyejare Thank you very much for your suggestion, I have updated the changes.
I have one question about the PR process. I am not sure whether I did the right steps or not.
When I did the update and submit the changes, I found the "Commit Suggestion" buttons are gray.
If I choose the "Commit suggestion" , the code can be updated and commit to the PR,  I do not need to update and git commit from my local dev env, Is that right?

2022-05-31 05:52 UTC, JacobCallahan commented
@yanpliu I believe that is more of a repository permissions issue than anything you're doing wrong. Thanks for updating

2022-05-31 06:05 UTC, yanpliu commented
> broker_settings.yaml.example
@JacobCallahan Thanks for your reply, what should I add to the broker_settings.yaml.example file? 
I  have go through the file  broker_settings.yaml.example ,
```
Container:
    instances:
        - docker:
            host_username: "<username>"
            host_password: "<plain text password>"
            host_port: None
            default: True
        - remote:
            host: "<remote hostname>"
            host_username: "<username>"
            host_password: "<plain text password>"
            **host_port: "<plain text port>"**----------------------------> add port in here?
```

2022-05-31 06:06 UTC, JacobCallahan commented
@yanpliu try near the top under `HOST_PASSWORD`

2022-05-31 06:08 UTC, yanpliu commented
> HOST_PASSWORD

Do you mean add 
```
# Host Settings
host_username: "root"
host_password: "<password>"
host_port:"<port>"  ---------> add here?
``

2022-05-31 06:28 UTC, yanpliu commented
> host_port to broker_settings.yaml.example file

@JacobCallahan Have added host_port to broker_settings.yaml.example file

2022-05-31 14:16 UTC, JacobCallahan requested changes
one minor change

2022-05-31 14:16 UTC, JacobCallahan commented on broker_settings.yaml.example
> +host_port: "<port>"
this should be host_ssh_port, correct?
```suggestion
host_ssh_port: "<port>"
```

2022-06-02 03:33 UTC, yanpliu commented
> one minor change

@JacobCallahan  Have already updated host_ssh_port in broker_settings.yaml.example file

2022-06-02 04:03 UTC, JacobCallahan approved these changes
ACK, thanks for the PR!

2022-06-02 04:03 UTC, merged