Let sftp_read return data
SatelliteQE/broker pull request #182
Opened 2023-01-18 17:28 UTC by ogajduse

This PR allows the user to get the `bytes` object without writing the data to the system.

I have used `sftp_read` method instead of creating a new one.

This PR will be used in SatelliteQE/robottelo#10547

2023-01-19 22:20 UTC, lpramuk approved these changes

2023-01-27 15:08 UTC, ogajduse commented on broker/session.py
> -        destination.touch()
I have removed the touch. I see no point in keeping it there as the file would get created anyway when we open and write to it.

2023-01-27 15:10 UTC, ogajduse commented
@JacobCallahan How about the test coverage for `sftp_read`? Do you want me to create it as a part of this PR?

2023-01-27 15:16 UTC, JacobCallahan commented
> @JacobCallahan How about the test coverage for `sftp_read`? Do you want me to create it as a part of this PR?

Yes, you can add some tests to the functional directory. Those operate on live hosts.

2023-01-27 16:07 UTC, rplevka approved these changes

2023-01-27 16:11 UTC, JacobCallahan requested changes

2023-01-27 16:11 UTC, JacobCallahan commented on broker/session.py
> +                        local.write(data)
We likely can simplify this a bit more. Since we are returning as bytes, we can read it into the object then either return that object or write it to the destination file.
```suggestion
            captured_data = bytes()
            for rc, data in remote:
                captured_data += data
            if return_data:
                return captured_data
            destination.write_bytes(data)
```

2023-01-30 14:48 UTC, ogajduse commented on broker/session.py
> +    def sftp_read(self, source, destination=None, return_data=False):
Done

2023-01-30 14:52 UTC, ogajduse commented on broker/session.py
> +                f = tar.extractfile(tar.getmember(Path(source).name))
Should we be worried about triplication of the data in the memory in case we transfer huge files?
See `data`, `all_data`, `f`.

2023-01-30 18:31 UTC, JacobCallahan commented on broker/session.py
> +                f = tar.extractfile(tar.getmember(Path(source).name))
could overwrite `data` on the join line. would at least help a bit. may also be able to `del all_data` in the line after we enter the context manager, but I don't know how it uses that reference

2023-01-30 18:38 UTC, JacobCallahan requested changes

2023-01-30 18:38 UTC, JacobCallahan commented on tests/conftest.py
> +    return request.param
ehhh setup is one thing, but I personally don't like moving test logic outside of the tests themselves. The tests can also differ in the breadth of functionality as well, which might be the better course of action. For example one test (per Provider) that tests all of the file actions.

2023-01-31 11:31 UTC, ogajduse commented on broker/session.py
> +                f = tar.extractfile(tar.getmember(Path(source).name))
Say I re-use `data` to store `all_data` as you suggested.
The reference to `data` is not used once we enter the context manager. So I tried to delete it as you suggested.
Using that patch I have successfully tested `ContainerSession.sftp_read` method using the `test_container_e2e_mp` test.
I will push a commit with this patch soon.

2023-01-31 11:41 UTC, ogajduse commented on tests/conftest.py
> +    return request.param
@JacobCallahan 
I agree, I can definitely improve this one.
I can imagine having one test per Provider only in the case of the Container provider. Hosts created using the AnsibleTower provider add significant time to the test time. The time it takes to spawn a host utilizing the Container provider is negligible compared to AnsibleTower.

For that reason, I would prefer having one functional test per provider as we do not "waste" time deploying instances.

Q1: Would you prefer code duplication over my solution? :smile: 

Q2: Aren't all Host objects supposed to behave roughly the same no matter the provider they are deployed with?

2023-01-31 14:13 UTC, ogajduse commented on broker/session.py
> +                f = tar.extractfile(tar.getmember(Path(source).name))
Modified in a7acaa4

2023-02-28 15:43 UTC, JacobCallahan requested changes

2023-02-28 15:43 UTC, JacobCallahan commented on tests/functional/test_containers.py
> +                assert data == Path(tmp.file.name).read_bytes(), "Received files do not match"
looks like you're just missing a newline
```suggestion
                assert data == Path(tmp.file.name).read_bytes(), "Received files do not match"

```

2023-02-28 15:56 UTC, ogajduse commented on tests/functional/test_containers.py
> +                assert data == Path(tmp.file.name).read_bytes(), "Received files do not match"
good catch!

2023-02-28 16:15 UTC, ogajduse commented
```
$ pytest tests/functional/test_containers.py -k test_container_e2e
========================================================================= test session starts =========================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0 -- /home/ogajduse/.virtualenvs/broker-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/ogajduse/repos/broker, configfile: pytest.ini
collected 8 items / 6 deselected / 2 selected                                                                                                                         

tests/functional/test_containers.py::test_container_e2e PASSED                                                                                                  [ 50%]
tests/functional/test_containers.py::test_container_e2e_mp PASSED                                                                                               [100%]

============================================================= 2 passed, 6 deselected in 85.14s (0:01:25) ==============================================================
```

2023-02-28 16:58 UTC, JacobCallahan approved these changes
ACK, nice!

2023-02-28 16:58 UTC, merged