REBASED: Make Broker able to log more verbosely
SatelliteQE/broker pull request #183
Opened 2023-01-20 15:33 UTC by ogajduse

I have rebased and modified #126.

## Description
TBD

2023-01-20 16:11 UTC, JacobCallahan commented on broker/settings.py
> +# temporary fix for dynaconf #751
hahahaha nice

2023-01-20 16:14 UTC, JacobCallahan requested changes
This looks promising, but no type annotations.

2023-01-23 17:02 UTC, ogajduse commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
Any feedback on this part? I am not sure if I like it. :smile: 

I do not like the fact that I have to create a new dictionary in order to redact the sensitive attributes.
Another way would be using some tricks that `logging` allows, but archived `logzero` does not. 

https://relaxdiego.com/2014/07/logging-in-python.html#redacting-logs-using-a-filter

2023-01-23 20:41 UTC, JacobCallahan commented on broker/helpers.py
> +    b_log.set_file_logging(value)
I would say so, yes. I typically want file logging verbosity the same or greater than console.

2023-01-23 20:43 UTC, JacobCallahan commented on broker_settings.yaml.example
> +    file_level: debug
if anything it could be flattened, but why the need to specify a different logging path?

```yaml
logging:
    console_level: info
    file_level: debug
    file_path: logs/broker.log
```

2023-01-23 20:47 UTC, JacobCallahan commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
what is the context where this would be an issue?

2023-01-23 20:59 UTC, ogajduse commented on broker_settings.yaml.example
> +    file_level: debug
I was just throwing an idea.
Would you like to change`level` to`console_level`? Otherwise we can resolve this thread.

2023-01-23 21:04 UTC, ogajduse commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
I do not like to copy the dict just for the purpose of logging which happens only when the level is set to >= `debug`.

Feel free to close this thread if you are fine with the current implementation.

2023-01-23 21:21 UTC, JacobCallahan commented on broker_settings.yaml.example
> +    file_level: debug
I get you. If there were more than just two nested fields, then it may be more natural to nest them. Otherwise, I think the flatter structure looks better.
We could change that to `console_level` for clarity, yes.

2023-01-23 21:23 UTC, JacobCallahan commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
I mean specifically why is it an issue to censor sensitive information in the log when anyone that has access to the log likely has access to the source of the information (where broker got it from)?

2023-01-24 12:52 UTC, ogajduse commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
It is just bad practice. See https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#data-to-exclude

2023-01-24 12:55 UTC, ogajduse commented on broker_settings.yaml.example
> +    file_level: debug
changed `level` to `console_level`

2023-01-24 20:02 UTC, JacobCallahan commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
I'm not overly concerned with that with Broker, but won't block you on it.

2023-01-24 20:02 UTC, JacobCallahan approved these changes

2023-01-26 13:36 UTC, ogajduse commented on broker/providers/__init__.py
> +            logger.debug(f"Checking {instance_name} against {candidate_redacted}")
I have introduced a different way of log redaction. Closing this thread.

2023-01-26 19:26 UTC, merged

2023-01-26 21:34 UTC, ogajduse commented
additionally, here are the test results:
```
$ pytest -v tests/functional/test_satlab.py
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0 -- /home/ogajduse/.virtualenvs/broker-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/ogajduse/repos/broker, configfile: pytest.ini
collected 11 items                                                                                                                                                                                                                          

tests/functional/test_satlab.py::test_checkout_scenarios[args_file0] PASSED                                                                                                                                                           [  9%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file1] PASSED                                                                                                                                                           [ 18%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file2] PASSED                                                                                                                                                           [ 27%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file3] PASSED                                                                                                                                                           [ 36%]
tests/functional/test_satlab.py::test_execute_scenarios[args_file0] PASSED                                                                                                                                                            [ 45%]
tests/functional/test_satlab.py::test_execute_scenarios[args_file1] PASSED                                                                                                                                                            [ 54%]
tests/functional/test_satlab.py::test_inventory_sync PASSED                                                                                                                                                                           [ 63%]
tests/functional/test_satlab.py::test_workflows_list PASSED                                                                                                                                                                           [ 72%]
tests/functional/test_satlab.py::test_workflow_query PASSED                                                                                                                                                                           [ 81%]
tests/functional/test_satlab.py::test_tower_host PASSED                                                                                                                                                                               [ 90%]
tests/functional/test_satlab.py::test_tower_host_mp PASSED                                                                                                                                                                            [100%]

============================================================================================================= warnings summary ==============================================================================================================
tests/functional/test_satlab.py: 10 warnings
  /home/ogajduse/.virtualenvs/broker-dev/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'infra-ansible-tower-01.infra.sat.rdu2.redhat.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================================================================== 11 passed, 10 warnings in 3799.06s (1:03:19) ================================================================================================
```