MacOS 12.x Installation notes added to readme
SatelliteQE/broker pull request #186
Opened 2023-01-26 14:15 UTC by damoore044

2023-01-26 14:55 UTC, JacobCallahan approved these changes
This looks good from a content perspective. However, I'd like to have @jyejare verify the installation instructions.

2023-01-26 18:02 UTC, Griffin-Sullivan commented on README.md
> +pip install . or pip install broker
Do we want to make the distinction here that `pip install .` will install locally where as `pip install broker` will install latest from PyPI?

2023-01-26 19:27 UTC, JacobCallahan commented on README.md
> +pip install . or pip install broker
Good idea, for those unfamiliar with the difference

2023-01-27 15:25 UTC, Griffin-Sullivan commented on README.md
> +pip install . or pip install broker
yeah I think that would be a nice change if you don't mind adding it

2023-01-27 15:46 UTC, Griffin-Sullivan approved these changes
Looks good!

2023-01-27 22:40 UTC, ogajduse approved these changes
ACK, one comment left.

2023-01-27 22:40 UTC, ogajduse commented on README.md
> +pip install ssh2-python
If you install broker you should not need to install `ssh2-python` additionally as this lib is a broker's requirement.

2023-01-27 22:42 UTC, ogajduse commented
@JacobCallahan Why are my checkmarks in my broker reviews grey while others have green? :thinking: :thinking: Hmmm

2023-01-27 23:01 UTC, JacobCallahan commented
> @JacobCallahan Why are my checkmarks in my broker reviews grey while others have green? :thinking: :thinking: Hmmm

haha it means you should be off and not paying attention right now

2023-02-01 14:56 UTC, jyejare requested changes
Some nitpick comments! 

@damoore044 I would also include the workaround for pycurl error and that is nothing but to uninstall existing pycurl and reinstall with command:
```
# PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L$(brew --prefix openssl)/lib" CPPFLAGS="-I$(brew --prefix openssl)/include" pip install --compile --install-option="--with-openssl" pycurl
```
That uses openssl library for pycurl installation than the default one.

2023-02-01 14:56 UTC, jyejare commented on README.md
> +pip install .   ( install Broker downloaded locally )
```suggestion
pip install .   ( install Broker cloned locally )   
```

2023-02-01 14:56 UTC, jyejare commented on README.md
> +# Installation MacOS 12.x
```suggestion
# Installation MacOS 12.x +
```

2023-02-01 14:56 UTC, jyejare commented on README.md
> +pip install .   ( install Broker downloaded locally )
```suggestion
pip install .   ( install Broker cloned locally )   
```

2023-02-01 14:56 UTC, jyejare commented on README.md
> +- Place the export statement in your working shell config; .bashrc .zshrc etc
```suggestion
- Place the export statement in your working shell config; .zshrc etc
```
Mac does provides zshrc only I think !

2023-02-01 15:06 UTC, damoore044 commented on README.md
> +- Place the export statement in your working shell config; .bashrc .zshrc etc
Mac ships with zsh, but bash can be brew installed and set as the main shell. Should we just have zsh since that is the default?

2023-02-02 10:52 UTC, jyejare approved these changes

2023-02-02 10:52 UTC, jyejare commented on README.md
> +- Place the export statement in your working shell config; .bashrc .zshrc etc
No Worries, we can mention both of them !

2023-02-02 11:07 UTC, merged