skip the broker check-in part of the context manager
SatelliteQE/broker pull request #196
Opened 2023-03-10 08:15 UTC by omkarkhatavkar

### Description

This PR adds a new optional parameter to the Broker class, `skip_checkin,` which can be set to `True` when instantiating the class to skip the check-in step when exiting the context.

If `skip_checkin` is not set or is set to False, the `__exit__` method will proceed with the normal check-in process, which includes attempting to perform a teardown on each host in the `_hosts` list and calling the `checkin` method to perform the final check-in step.

This change is useful when the `Broker` instance is being used in a context where a check-in is not necessary or desired, such as when performing read-only operations on remote servers.

2023-03-10 13:52 UTC, JacobCallahan requested changes
I'm not sure this should be specified on the class level, since it may be too broad. However, we can discuss intended uses and implementation in chat. This may ultimately be the least clumsy way of adding the skip functionality.

2023-03-10 13:52 UTC, JacobCallahan commented on broker/broker.py
> +        self.skip_checkin =  kwargs.pop("skip_checkin", False)
If this is going to only affect checkins from the context manager, then I think the argument needs to be a bit more clear for that. Otherwise, setting this on class instantiation could be interpreted to mean that this Broker instance won't checkin anything.
```suggestion
        self.skip_context_checkin =  kwargs.pop("skip_context_checkin", False)
```

2023-03-13 20:43 UTC, JacobCallahan requested changes
One key part of this is allowing the behavior only when in the context manager. This implementation would also disallow checkins outside of the context manager.

You'll need to add an argument to checkin like `in_context=True` and checking for that before the list comprehension filtering no_checkin hosts
```python
if in_context:
    do your comprehension filter
```

2023-03-13 20:43 UTC, JacobCallahan commented on broker/broker.py
> +        if isinstance(hosts, list):
Actually this section should probably be like this
```python
        elif not isinstance(hosts, list):
            hosts = [hosts] if getattr(hosts, '_skip_context_checkin', False) else []
        else:
            hosts = [host for host in hosts if not getattr(host, '_skip_context_checkin', False)]
```
Though it could also be done by nesting and else under the dict check and going from there.
```python
        else:
            if not isinstance(hosts, list):
                hosts = [hosts]
            hosts = [host for host in hosts if not getattr(host, '_skip_context_checkin', False)]
```

2023-03-14 06:31 UTC, omkarkhatavkar commented on broker/broker.py
> +        if isinstance(hosts, list):
I think the 2nd one more correct I feel.

2023-03-14 06:50 UTC, omkarkhatavkar commented
> One key part of this is allowing the behavior only when in the context manager. This implementation would also disallow checkins outside of the context manager.
> 
> You'll need to add an argument to checkin like `in_context=True` and checking for that before the list comprehension filtering no_checkin hosts
> 
> ```python
> if in_context:
>     do your comprehension filter
> ```

Okay, understood. I've added an additional layer of security to the check-in process.

2023-03-14 13:16 UTC, omkarkhatavkar commented on broker/broker.py
> +        self.checkin(in_context=True)
Implementing this way, we will be eliminating the use of fixture which does not use the context manager. 
e.g.
```
@pytest.fixture(scope='session')
def session_satellite_host(satellite_factory):
    """A fixture that provides a Satellite based on config settings"""
    new_sat = satellite_factory()
    yield new_sat
    new_sat.teardown()
    Broker(hosts=[new_sat]).checkin()

```

2023-03-22 21:00 UTC, JacobCallahan approved these changes

2023-03-22 21:00 UTC, merged