refactor logging
SatelliteQE/broker pull request #209
Opened 2023-04-25 07:42 UTC by rplevka

Replaces deprecated `logzero` by a ntaive `logging` lib
inroduces logger hierarchy per module (handler, formatter inheritance, ...)

This complements the changes introduced in robottelo by https://github.com/SatelliteQE/robottelo/pull/11332

TBD:
- [ ] figure out initialization when broker is run from CLI (`__main__`)
- [ ]  figure out a way of adding broker's external lib loggers (`awxkit`,...) to the hierarchy

2023-04-25 13:38 UTC, JacobCallahan requested changes
Some major questions along with a need for screenshots of debug-level logging and potentially an exception being raised. We will still need colorized logging levels.

2023-04-25 13:38 UTC, JacobCallahan commented on broker/logger.py
> +    path=None,
Why default to none instead of Broker's default log path?

2023-04-26 09:51 UTC, ogajduse commented on broker/__init__.py
> +#VMBroker = Broker
Good question.
I have checked out SatelliteQE/robottelo#1332 and installed broker from this PR/branch and I reverted the patch in this `__init__.py` file. I put breakpoint into both logger setup functions in broker and [here is](https://pastebin.com/12ubYuC6) the call stack.

We can see that broker's logger gets initialized during the import time. That is not ideal, we want to initialize broker logger once `setup_logger` is called, not when it is imported.

`from broker.logger import setup_logger as broker_log_setup` import imports `from broker.broker import Broker` which imports `from broker.hosts import Host` which calls `logger = init_logger(__name__)` that initializes the logger.

Do you have any idea what could be a different approach to avoid setting the logger up during the import time?

2023-05-02 20:37 UTC, JacobCallahan commented on broker/__init__.py
> +#VMBroker = Broker
Let's reframe this a bit. 
Why try to avoid the initial logger setup? 
What is gained from finding a way around it?
What is lost from user experience by implementing workarounds?

It's not always easy to do this in a way that satisfies what @rplevka wants here while maintaining a nice API and reducing waste. One potential option is for Broker to use its own logging wrapper that lazily sets up the logging interface.

2023-05-04 13:50 UTC, rplevka commented on broker/__init__.py
> +#VMBroker = Broker
Hi.
My primary motivation was to redesign broker logging in a way, so it can fully give away control over its setup to library that uses it (robottelo).
The thing with robottelo is, that I was looking to setup different handlers (that would log to their own files) for different pytest objects - especially fixtures.
It is possible to control this from the appropriate pytest hook functions, however, these are being entered quite late in the process (by that time, the broker logger is self-initialized by only refering to the module using import statements - thus, it generates unwanted loggers and logfiles that are outside of robottelo control.

I don't have a strong opinion about how this  is supposed to work, so I am opened to some ideas, but this design is something I came to while trying to solve a problem of a proper structured logging (to know what logs belong to what part of the session) for purposes of log parsing and pushing towards reporting platforms.

2023-05-04 20:42 UTC, JacobCallahan commented on broker/__init__.py
> +#VMBroker = Broker
Due to import sequences, this isn't something that we can do easily in Python. In my opinion, it's not a big enough concern to justify changes like this. If Broker creates a log file and potentially a few logs before Robottelo redirects its logger, that's not a big deal. Please revert changes like the ones here.

2025-11-05 05:35 UTC, closed without merging