Custom socket connect timeout in Session()
SatelliteQE/broker pull request #210
Opened 2023-04-30 17:35 UTC by akhil-jha

What?
Let the user give a timeout for socket.connect(). Default is still 60.

Why? 
In cloud VMs, we get Connection Refused as the machine is not ready to take ssh connection just yet. Increasing the timeouts(reties) solves the issue.

2023-05-01 12:09 UTC, mshriver approved these changes

2023-05-01 12:23 UTC, Griffin-Sullivan approved these changes

2023-05-02 07:46 UTC, akhil-jha commented
**Test:**
```
ipdb> with BrokerSession(username="ec2-user", hostname=ip, key_filename=pubkey_data["private_key_path"], socket_connect_timeout=500,) as host:
                assert "hostname" in host.run("rpm -q hostname").stdout
                host.run("hostname").stdout
 

[WARNING 230502 13:07:53] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 1 seconds.
[WARNING 230502 13:07:54] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 2 seconds.
[WARNING 230502 13:07:56] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 4 seconds.
[WARNING 230502 13:08:00] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 8 seconds.
[WARNING 230502 13:08:09] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 16 seconds.
[WARNING 230502 13:08:25] Tried cmd=<built-in method connect of socket object at 0x7f0ecc1353a0> with cmd_args=[('54.197.154.60', 22)], cmd_kwargs={} but received err=ConnectionRefusedError(111, 'Connection refused')
    Trying again in 32 seconds.

ipdb>

'ip-172-31-93-71.ec2.internal\n'
```

2023-05-02 17:03 UTC, akhil-jha commented
Oops, I didn't checkout Host() 🤦‍♂️

2023-05-02 20:14 UTC, JacobCallahan commented
It would indeed, which is why I asked. Most users make connections from the Host objects themselves instead of directly with a Session object. Perhaps, if you make it a configurable option (with a sane default), then that would help them. Otherwise, it would need to be passed down during host object creation.

2023-05-04 10:55 UTC, akhil-jha commented
```
from broker.hosts import Host
```
```
        for ip in host_ips:
            host = Host(
                username="ec2-user",
                hostname=ip,
                key_filename=pubkey_data["private_key_path"],
                socket_connect_timeout=500,
            )
            host.execute("rpm -q hostname").stdout
```
```
$ ENV_FOR_DYNACONF=stage_proxy iqe tests plugin provisioning -k test_aws_reservations_e2e_launch_template -k test_aws_reservations_e2e_launch_template
...
======================================================== 1 passed, 22 deselected in 137.50s (0:02:17) ========================================================
```

2023-05-04 20:46 UTC, JacobCallahan approved these changes

2023-05-04 20:46 UTC, JacobCallahan commented
@akhil-jha is this ready for merge, or did you want to do some more testing on it?

2023-05-05 13:47 UTC, JacobCallahan requested changes
Let's switch from this implementation to simply passing this timeout
https://github.com/SatelliteQE/broker/blob/master/broker/hosts.py#L57
to the Sessions created here
https://github.com/SatelliteQE/broker/blob/master/broker/hosts.py#L65

I don't know why I removed it in #151

2023-05-07 16:08 UTC, akhil-jha commented on broker/hosts.py
> +            timeout=timeout
Dependent on `settings.HOST_CONNECTION_TIMEOUT`. If not settings, It'll be none. That means no retry.

2023-05-08 19:27 UTC, JacobCallahan approved these changes
ACK, thanks for the revision!

2023-05-08 19:27 UTC, JacobCallahan commented on broker/hosts.py
> +            timeout=timeout
If None, simple_retry should still get your default of `60` so I think we're good here!

2023-05-09 12:57 UTC, akhil-jha commented on broker/hosts.py
> +            timeout=timeout
Ah right.okay yes.

2023-05-09 12:57 UTC, akhil-jha commented on broker/settings.py
> +    Validator("HOST_CONNECTION_TIMEOUT", default=60),
So you want to keep it? or should I remove it?

2023-05-11 17:45 UTC, JacobCallahan commented on broker/settings.py
> +    Validator("HOST_CONNECTION_TIMEOUT", default=60),
let's try to keep this version, but we'll need to pay attention to automation after this release is live.

2023-05-11 17:50 UTC, JacobCallahan approved these changes

2023-05-11 17:50 UTC, merged