Assign name and hostname to the host if it is constructed
SatelliteQE/broker pull request #213
Opened 2023-05-11 16:25 UTC by ogajduse

Let's have the following host
```python
class IPAHost(Host):
    def __init__(self, sat_obj, **kwargs):
        self.satellite = sat_obj
        kwargs['hostname'] = kwargs.get('hostname', settings.ipa.hostname)
        # Allow the class to be constructed from kwargs
        kwargs['from_dict'] = True
        kwargs.update(
            {
                'base_dn': settings.ipa.basedn,
                'disabled_user_ipa': settings.ipa.disabled_ipa_user,
            }
        )
        super().__init__(**kwargs)
```

Then the following code snippet
```python
sat = Host('foo.bar')
ipahost = IPAHost(sat)
ipahost.hostname
```
will fail with `AttributeError: 'IPAHost' object has no attribute 'hostname'`

The `Host` `__init__` stores the `hostname` and the `name` in args, not in `kwargs`. So we need to set `name` and `hostname`  directly regardless of what `from_dict` is set to.

Ref: SatelliteQE/robottelo#11445
This is most likely the first host that is using `from_dict`. :smirk:

2023-05-11 16:40 UTC, ogajduse commented
Another approach I can think of is to remove the `from_dict` logic and update `__dict__` every time.

2023-05-11 17:19 UTC, JacobCallahan commented
I like your last comment. Additionally, now that hostname and name aren't technically required. We can remove them as named arguments and just take it all in as kwargs. If we go that route though, it would be good to add a docstring telling people which combination of arguments are required.

2023-05-15 12:32 UTC, Griffin-Sullivan commented
Should I review this version or are we changing the PR? @ogajduse

2023-05-15 13:25 UTC, ogajduse commented
@Griffin-Sullivan @JacobCallahan Implemented.
Feel free to review it now.

2023-05-15 13:26 UTC, ogajduse commented on broker/hosts.py
> +        self.__dict__.update(kwargs) # Make every other kwarg an attribute
"attribute" or "property"?

2023-05-15 15:44 UTC, JacobCallahan requested changes

2023-05-15 15:44 UTC, JacobCallahan commented on broker/hosts.py
> +            Path to SSH key file to use for SSH connection
I think this is a little bit extra 😃 
Maybe we just do something like this.
```suggestion
        Expected kwargs:
          hostname: str - Hostname or IP address of the host, required
          name: str - Name of the host
          username: str - Username to use for SSH connection
          password: str - Password to use for SSH connection
          connection_timeout: int - Timeout for SSH connection
          port: int - Port to use for SSH connection
          key_filename: str - Path to SSH key file to use for SSH connection
```

2023-05-15 17:50 UTC, Griffin-Sullivan approved these changes
Ran some functional tests and used ipython to make sure host creation works with hostname and IP and doesn't work when missing either. I also verified that changing the hostname and IP to `null` before checkin doesn't throw an error once the checkin completes.

2023-05-16 11:59 UTC, ogajduse commented on broker/hosts.py
> +        self.hostname = kwargs.get("hostname") or kwargs.get("ip", None)
Yup, I saw that one, but I kept it there. I will remove it.

2023-05-16 13:38 UTC, JacobCallahan approved these changes

2023-05-17 15:47 UTC, JacobCallahan approved these changes

2023-05-17 15:50 UTC, merged