Add Ruff as a code checker
SatelliteQE/broker pull request #222
Opened 2023-07-07 20:35 UTC by JacobCallahan

Ruff is a newer code checker that is written in Rust and is very fast. Adding this now with a number of pretty sane checks to start with. I recommend having ruff integrated into your editor to pick out issues as you write code.

2023-07-07 20:49 UTC, JacobCallahan commented
Available rules can be found here: https://beta.ruff.rs/docs/rules/

If you find one you think should be added, comment with your reasoning.

2023-07-08 00:22 UTC, JacobCallahan commented
All tests passed locally, including functional for all providers.
![Screenshot from 2023-07-07 20-21-56](https://github.com/SatelliteQE/broker/assets/6618303/da0d3975-bc16-424b-80a2-c2c35d794bd6)

2023-07-11 09:48 UTC, ogajduse requested changes

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "D407", # Section name underlining
Why do we need to ignore D407?

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "D107", # Missing docstring in __init__
Why can't `__init__` have a docstring too?

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "D406", # Section name should end with a newline
What is the reason for ignoring D406?

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "PLR0913", # Too many arguments to function call ({c_args} > {max_args})
Isn't it better to define a sane number of max arguments?
https://beta.ruff.rs/docs/settings/#pylint-max-args

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "PLC0208", # Use a sequence type instead of a `set` when iterating over values
ruff `0.0.277` still reports this issue even though https://github.com/astral-sh/ruff/releases/tag/v0.0.276 fixed the false positive.

I would like to see this one selected, rather than ignored.

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +    "D213", # Multi-line docstring summary should start at the second line
Why can't broker be compliant with pydocstyle recommendations?
I would like to see at least D202 not being ignored.

2023-07-11 09:48 UTC, ogajduse commented on ruff.toml
> +# "script/*" = ["T20"]
HA is definitely a great source to get inspiration from :heart:

2023-07-11 20:31 UTC, JacobCallahan commented on ruff.toml
i've considered that, but am a bit on the fence about it. right now we don't have many tool that would typically go in a pyproject.toml, this one being a large exception. perhaps if we added pre-commit with black and ruff...

2023-07-11 20:31 UTC, JacobCallahan commented on broker/broker.py
> +        logger.debug(f"Tell Jake the exception was: {err}")
ha yep! gotta see what these are in automation

2023-07-11 20:34 UTC, JacobCallahan commented on broker/helpers.py
> +                    lambda item: eval(  # noqa: S307
unfortunately, no. we need to pass in the filterable data structure and ast.literal_eval can't do that.

2023-07-11 20:40 UTC, JacobCallahan commented on broker/helpers.py
> +            if request := _frame.frame.f_locals.get("request"):  # noqa: F821
This is largely due to the order in which the frames are available, so it gives us the ability to "look back" at the previous frame to get the request object from the actual fixture instead of the pytest-internal frame we'd be at otherwise.

2023-07-11 20:42 UTC, JacobCallahan commented on broker/providers/container.py
> +        except Exception as err:  # noqa: BLE001 - This could be a few things
it could be, but at this point I'm not sure what all we could hit here.

2023-07-11 20:50 UTC, JacobCallahan commented on ruff.toml
> +    "D407", # Section name underlining
We don't really use section headings and I think it's ugly.

2023-07-11 20:53 UTC, JacobCallahan commented on ruff.toml
> +    "D107", # Missing docstring in __init__
Many times the contents of an __init__ docstring is a repetition from the class' own docstring. I find docstrings like "Initialize the class" to be useless. If I could turn it off for all other common dunder methods, I would.

2023-07-11 20:53 UTC, JacobCallahan commented on ruff.toml
> +    "D406", # Section name should end with a newline
See comment about D407 ;)

2023-07-11 20:55 UTC, JacobCallahan commented on ruff.toml
> +    "PLR0913", # Too many arguments to function call ({c_args} > {max_args})
Sane is up to personal preference and tool compatibility. Most of the times this was triggered in Broker was due to click command options.

2023-07-11 21:03 UTC, JacobCallahan commented on ruff.toml
> +    "PLC0208", # Use a sequence type instead of a `set` when iterating over values
oh good catch. looks like it's fixed in 0.0.277

2023-07-11 21:08 UTC, JacobCallahan commented on ruff.toml
> +    "D213", # Multi-line docstring summary should start at the second line
We can use D202, but I don't like the others.

2023-07-11 21:10 UTC, JacobCallahan commented on ruff.toml
> +# "script/*" = ["T20"]
oh definitely, they were the standard for most of this file! however, let's go ahead and remove this ;)

2023-07-11 21:16 UTC, JacobCallahan commented
@ogajduse thanks for the thorough review! Updated all I saw to address and a little more.

2023-07-12 04:37 UTC, JacobCallahan commented on broker/logger.py
> +        if isinstance(data, list | tuple):
This change is incompatible with Python 3.9. Which brings up a question: is it too soon to drop 3.9 support with Broker 0.4? We do have Python 3.12 coming out later this year, so it won't be much longer, but maybe now is too soon..

2023-07-12 13:14 UTC, Griffin-Sullivan commented on broker/logger.py
> +        if isinstance(data, list | tuple):
I would say go ahead and keep it. If anyone is using 3.9 they shouldn't...

2023-07-12 18:08 UTC, JacobCallahan commented on ruff.toml
Actually... newest change switched us over to pyproject.toml completely

2023-07-18 14:42 UTC, ogajduse approved these changes

2023-07-18 16:39 UTC, JacobCallahan commented on broker/broker.py
> +        logger.debug(f"Tell Jake the exception was: {err}")
I'll keep as-is since the creation of the exception class below will also log as an error.

2023-07-18 16:39 UTC, merged