Added system and location information for catalog-info.yaml
SatelliteQE/broker pull request #256
Opened 2023-12-13 04:25 UTC by rujutashinde

Added system and location information so the Broker tool can be seen correctly under quality-community domain

2023-12-13 04:26 UTC, rujutashinde commented
@JacobCallahan I put in a new PR instead of PR #254  we can close that one, so we are not waiting on updates there

2023-12-13 18:43 UTC, JacobCallahan requested changes
Missing some trailing newlines. Also, can you update your commit message to describe the changes, specifically why the additional file is used for metadata instead of the original?

2023-12-13 18:43 UTC, JacobCallahan commented on catalog-info.yaml
> +    - ./catalog/system/broker.yaml
```suggestion
    - ./catalog/system/broker.yaml

```

2023-12-13 18:43 UTC, JacobCallahan commented on catalog/system/broker.yaml
> +  domain: quality-community/quality-community
```suggestion
  domain: quality-community/quality-community

```

2023-12-15 19:14 UTC, JacobCallahan approved these changes

2023-12-15 19:14 UTC, merged