Add optional provider label support
SatelliteQE/broker pull request #277
Opened 2024-03-18 22:10 UTC by rplevka

Extend broker's AnsibleTower and Container provider functionality to pass labels to be set to the spawned resources.
It accepts a string of comma-separated label values.
Broker then uses awxkit session to resolve their id's (required for the job `/launch` payload) and eventually creates the non-existing labels.

User is required to have granted permissions for creating new labels (if that's even a thing) on AAP.

Plan is to implement the labeling functionality to all providers that have support of labels, e.g.
https://docs.docker.com/config/labels-custom-metadata/

example usage:
```
# ansible tower provider
$ broker execute deploy-rhel --provider-labels foo=bar,baz
```
translates to:
![Selection_674](https://github.com/SatelliteQE/broker/assets/11773362/cfeb3c17-8c88-4752-b616-f4acebfb4314)
(AAP labels are single string items)

```
# container provider with additional labels configured in the nick:

nick:

  rhel8_docker:
    container_host: "ubi8:latest"
    environment:
      BUILD_URL: "https://intergalactic.planetary/planetary/intergalactic"
    provider_labels:
      nick_label_1: myval1
      nick_label_2: myval2

$ broker checkout --nick rhel8_docker --provider-labls cli1=val1,nick_label_2=overriden_by_cli_param
[INFO 240418 14:13:37] Using provider Container to checkout
[INFO 240418 14:13:45] Host: 97c993636de8
```
translates to:
```
$ docker inspect 97c993636de8
...
            "Labels": {
                "architecture": "x86_64",
                "broker.jenkins.url": "",
                "broker.nick_label_1": "myval1",
                "broker.nick_label_2": "myval2",
                "broker.origin": "broker_cli:rplevka",
               ...
...
```

2024-04-18 13:04 UTC, JacobCallahan requested changes
Can you add a functional test each for tower and containers? 
I think we can just skip beaker for now since I'm not sure that labels are a thing there (and it is much less commonly used).

Also, how well are these labels recovered after a sync?

2024-04-18 13:04 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +                {f"_broker_label_{label[0]}": "=".join(label[1:]) for label in labels.items()}
each label getting its own attribute may be a bit much. what do you think about collecting these under a `_provider_labels` list? or maybe even just `labels`?

2024-04-18 13:37 UTC, rplevka commented on broker/commands.py
> +    " labels (e.g. '-l k1=v1,k2=v2,k3=v3=z4').",
i somehow wanted to demo, that multiple `=` won't be an issue (translates to `k3: `v3=z4`) but apparently I ended up confusing you :)

2024-04-18 13:39 UTC, rplevka commented on broker/commands.py
> +def extend(vm, provider_labels, background, all_, sequential, filter, **kwargs):
...well, I am happy to drop this, but on the other hand - it generates an AAP job. And perhaps it deserves to have the labels assigned too. I doubt we would use it too much tho

2024-04-18 13:47 UTC, rplevka commented on broker/providers/ansible_tower.py
> +                {f"_broker_label_{label[0]}": "=".join(label[1:]) for label in labels.items()}
This would require additional parsing logic to be implemented in AT (another round of `.split('=')`). What are the downsides of passing them as extra vars straight away?

2024-04-19 15:44 UTC, bherrin3 commented on broker/commands.py
> +def extend(vm, provider_labels, background, all_, sequential, filter, **kwargs):
the main place I care about labels is when we are creating or destroying resources in providers. This causes a need for load and resource cost. 

Since extend is purely an SLA thing, I would state labels are not required here, for now.

2024-04-19 19:42 UTC, JacobCallahan commented on broker/commands.py
> +def extend(vm, provider_labels, background, all_, sequential, filter, **kwargs):
cool. let's remove here then

2024-04-23 14:48 UTC, JacobCallahan requested changes
Just a few more things. Can you also resolve the merge conflicts?

2024-04-23 14:48 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +                    result = self.v2.labels.post(
do we expect both of these to possibly give us a permission error or just the label creation? i typically like to isolate try/except to a single suspect endpoint.

2024-04-23 14:48 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +                raise exceptions.PermissionError
can you add a message here telling the user that the permission error is because they were unable to read/create the label?

2024-04-23 14:48 UTC, JacobCallahan commented on tests/functional/test_satlab.py
> +        mocker.patch.object()
why the use of pytest-mock here? also, there's a missing newline

2024-04-24 16:31 UTC, rplevka commented on broker/providers/ansible_tower.py
> +                    result = self.v2.labels.post(
so, according @bherrin3 , both of these should be "Free" and should not require any extra permissions. any authenticated, regular user, should be able to list and create labels.
Would you prefer to keep the try/except block in place just for a case?

2024-04-24 16:51 UTC, bherrin3 commented on broker/providers/ansible_tower.py
> +                    result = self.v2.labels.post(
Verified and tested with non-admin users.

Removal of labels is purely an administrative function that tower does itself, but would never happen due to the way we are using labels and not cleaning up jobs.

If listing labels is desired, I would see this as a function of broker for the AnsibleTower provider as that API endpoint literally has the count and all labels in a data structure.

2024-04-25 06:20 UTC, rplevka commented on tests/functional/test_satlab.py
> +        mocker.patch.object()
that was a part of my experiment, not intended to end up here (already removed)

2024-04-25 09:41 UTC, rplevka commented on broker/providers/ansible_tower.py
> +                    result = self.v2.labels.post(
done

2024-04-25 09:42 UTC, rplevka commented on broker/providers/ansible_tower.py
> +                raise exceptions.PermissionError
obsoleted by removing the whole try-except block

2024-04-29 12:36 UTC, rplevka commented on pyproject.toml
> +    "pytest-mock",
ah, right. thanks for reminder. removed.

2024-05-01 19:41 UTC, JacobCallahan approved these changes

2024-05-01 19:41 UTC, merged