Add support for multiple ssh backends
SatelliteQE/broker pull request #282
Opened 2024-04-08 20:16 UTC by tpapaioa

- Add support for hussh and ansible-pylibssh libraries
- Add `ssh_backend: ssh2-python312` default setting to `broker_settings.yaml.example`. To use `hussh` or `ansible-pylibssh`, install the package and then override the setting in the local `broker_settings.yaml` file, or with the `BROKER_SSH_BACKEND` environment variable:
```
$ pip install hussh
$ BROKER_SSH_BACKEND="hussh" broker inventory
[INFO 240408 14:39:58] SSH_BACKEND='hussh'
[...]

$ pip install ansible-pylibssh
$ BROKER_SSH_BACKEND="ansible-pylibssh" broker inventory
[INFO 240408 16:15:32] SSH_BACKEND='ansible-pylibssh'
[...]
```

Verified functional tests:

```
$ BROKER_SSH_BACKEND="hussh" pytest -k test_satlab
=== test session starts ===
[...]
collected 68 items / 58 deselected / 10 selected

tests/functional/test_satlab.py::test_checkout_scenarios[args_file0] PASSED [ 10%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file1] PASSED [ 20%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file2] PASSED [ 30%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file3] PASSED [ 40%]
tests/functional/test_satlab.py::test_execute_scenarios[args_file0] PASSED  [ 50%]
tests/functional/test_satlab.py::test_inventory_sync PASSED                 [ 60%]
tests/functional/test_satlab.py::test_workflows_list PASSED                 [ 70%]
tests/functional/test_satlab.py::test_workflow_query PASSED                 [ 80%]
tests/functional/test_satlab.py::test_tower_host PASSED                     [ 90%]
tests/functional/test_satlab.py::test_tower_host_mp PASSED                  [100%]
=== 10 passed, 58 deselected, 49 warnings in 4216.30s (1:10:16) ===

****

$ BROKER_SSH_BACKEND="ansible-pylibssh" pytest -k test_satlab
=== test session starts ===
[...]
collected 68 items / 58 deselected / 10 selected

tests/functional/test_satlab.py::test_checkout_scenarios[args_file0] PASSED   [ 10%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file1] PASSED   [ 20%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file2] PASSED   [ 30%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file3] PASSED   [ 40%]
tests/functional/test_satlab.py::test_execute_scenarios[args_file0] PASSED    [ 50%]
tests/functional/test_satlab.py::test_inventory_sync PASSED                   [ 60%]
tests/functional/test_satlab.py::test_workflows_list PASSED                   [ 70%]
tests/functional/test_satlab.py::test_workflow_query PASSED                   [ 80%]
tests/functional/test_satlab.py::test_tower_host PASSED                       [ 90%]
tests/functional/test_satlab.py::test_tower_host_mp PASSED                    [100%]
[...]
=== 10 passed, 58 deselected, 43 warnings in 3985.79s (1:06:25) ===
```

2024-04-09 14:13 UTC, tpapaioa commented
Functional tests on `ssh2-python312`:
```
$ BROKER_SSH_BACKEND="ssh2-python312" pytest -k test_satlab
[...]
collected 68 items / 58 deselected / 10 selected

tests/functional/test_satlab.py::test_checkout_scenarios[args_file0] PASSED  [ 10%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file1] PASSED  [ 20%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file2] PASSED  [ 30%]
tests/functional/test_satlab.py::test_checkout_scenarios[args_file3] PASSED  [ 40%]
tests/functional/test_satlab.py::test_execute_scenarios[args_file0] PASSED   [ 50%]
tests/functional/test_satlab.py::test_inventory_sync PASSED                  [ 60%]
tests/functional/test_satlab.py::test_workflows_list PASSED                  [ 70%]
tests/functional/test_satlab.py::test_workflow_query PASSED                  [ 80%]
tests/functional/test_satlab.py::test_tower_host PASSED                      [ 90%]
tests/functional/test_satlab.py::test_tower_host_mp PASSED                   [100%]
[...]
=== 10 passed, 58 deselected, 45 warnings in 4045.79s (1:07:25) ===
```

2024-04-09 14:37 UTC, tpapaioa commented
Updated functional test ids for parametrized scenario tests, to show the scenario file name instead of the default, less informative, ids created by pytest.

Before:
```
$ pytest --co -k 'test_checkout_scenarios or test_execute_scenarios'
[...]
collected 68 items / 58 deselected / 10 selected

<Dir broker>
  <Dir tests>
    <Dir functional>
      <Module test_containers.py>
        <Function test_checkout_scenarios[args_file0]>
        <Function test_checkout_scenarios[args_file1]>
        <Function test_execute_scenarios[args_file0]>
      <Module test_rh_beaker.py>
        <Function test_checkout_scenarios[args_file0]>
        <Function test_checkout_scenarios[args_file1]>
      <Module test_satlab.py>
        <Function test_checkout_scenarios[args_file0]>
        <Function test_checkout_scenarios[args_file1]>
        <Function test_checkout_scenarios[args_file2]>
        <Function test_checkout_scenarios[args_file3]>
        <Function test_execute_scenarios[args_file0]>
```

After:
```
$ pytest --co -k 'test_checkout_scenarios or test_execute_scenarios'
[...]
collected 68 items / 58 deselected / 10 selected

<Dir broker>
  <Dir tests>
    <Dir functional>
      <Module test_containers.py>
        <Function test_checkout_scenarios[checkout_ch-d_ubi8]>
        <Function test_checkout_scenarios[checkout_ch-d_ubi8_2]>
        <Function test_execute_scenarios[execute_ch-d_ubi8]>
      <Module test_rh_beaker.py>
        <Function test_checkout_scenarios[checkout_test_job-2]>
        <Function test_checkout_scenarios[checkout_test_job]>
      <Module test_satlab.py>
        <Function test_checkout_scenarios[checkout_latest_sat]>
        <Function test_checkout_scenarios[checkout_latest_rhel]>
        <Function test_checkout_scenarios[checkout_rhel91]>
        <Function test_checkout_scenarios[checkout_sat_613]>
        <Function test_execute_scenarios[execute_templates_list]>
```

2024-04-09 21:10 UTC, JacobCallahan requested changes
Great work overall! Just some relatively minor notes.

2024-04-09 21:10 UTC, JacobCallahan commented on broker/session.py
> +        from broker.ssh_session import BaseSession as Session
Why can't the `ssh_session` module's contents live in this module?

2024-04-09 21:10 UTC, JacobCallahan commented on broker/session.py
> +        """Needed for simple compatibility with Session."""
Nice. I always do this.

2024-04-09 21:10 UTC, JacobCallahan commented on broker/ssh_session_hussh.py
> +class Session:
This class seems a bit heavy. Maybe if you used Hussh's Connection class as a parent, some things could be slimmed down here.

2024-04-09 21:10 UTC, JacobCallahan commented on pyproject.toml
> -    "ssh2-python312",
not sure if we should remove this yet, but it's something to think about. maybe since this will be a 0.5 release it's more expected to break existing workflows.

2024-04-10 20:34 UTC, tpapaioa commented on broker/session.py
> +logger.info(f"{SSH_BACKEND=}")
Done.

2024-04-10 20:34 UTC, tpapaioa commented on broker/session.py
> +        from broker.ssh_session_ssh2 import InteractiveShell, Session  # noqa: F401
Moved modules to binds directory.

2024-04-10 20:36 UTC, tpapaioa commented on broker/session.py
> +        from broker.ssh_session import BaseSession as Session
I had originally thought of using `BaseSession` as a base class for the individual backend classes. I've updated the import logic to create the default session class if a backend can't be imported.

2024-04-10 20:38 UTC, tpapaioa commented on broker/ssh_session_hussh.py
> +class Session:
A lot of the methods have to do small logic around the `ensure_dir` and `return_data` params. Could those maybe be implemented within hussh? If so, then this session class could pretty much inherit everything from the hussh class.

2024-04-10 20:39 UTC, tpapaioa commented on pyproject.toml
> -    "ssh2-python312",
I took it out while testing w/ PRT and forgot to add it back. Fixed.

2024-04-11 21:31 UTC, JacobCallahan commented on broker/ssh_session_hussh.py
> +class Session:
Ok, we'll leave as-is for now. If I add this to Hussh (likely), then I'll update this class.

2024-04-15 19:34 UTC, JacobCallahan approved these changes
ACK, thanks for taking this on!

2024-04-15 19:35 UTC, merged