Fix minor bugs in foreman bind
SatelliteQE/broker pull request #300
Opened 2024-07-10 09:20 UTC by dosas

* Remove invalid provider argument
* Handle additional error message format
* Write tests for interpret_response

2024-07-10 20:03 UTC, JacobCallahan requested changes

2024-07-10 20:03 UTC, JacobCallahan commented on tests/providers/test_foreman.py
> +        )
```suggestion
    )
```

2024-07-10 20:03 UTC, JacobCallahan commented on tests/providers/test_foreman.py
> +                         )
here's some more ruff-style formatting. perhaps we should turn on formatting checks for the test directory.
```suggestion
@pytest.mark.parametrize(
    "response,expected,context",
    [
        ({1: 2}, {1: 2}, nullcontext()),
        (
            {"error": {"message": "Unable to authenticate user"}},
            None,
            pytest.raises(AuthenticationError),
        ),
        (
            {"error": {"full_messages": "foo", "message": "bar"}},
            None,
            pytest.raises(ForemanBindError),
        ),
        ({"errors": {"base": "foo"}}, None, pytest.raises(ForemanBindError)),
        ({"error": {"full_messages": ["bar"]}}, None, pytest.raises(ForemanBindError)),
    ],
)
```

2024-07-11 07:47 UTC, dosas commented on broker/binds/foreman.py
> +            self.foreman_username = settings.foreman.foreman_username
That is what I had first but then changed it because of some test problems and forgot to revert it ...

2024-07-11 07:52 UTC, dosas commented on tests/providers/test_foreman.py
> +                         )
Yes, please, I prefer it very much when such problems' are solved by a machine.

2024-07-11 18:04 UTC, JacobCallahan approved these changes

2024-07-11 18:04 UTC, merged