Introduction of broker config cli and much more!
SatelliteQE/broker pull request #317
Opened 2024-09-17 18:01 UTC by JacobCallahan

The initial change of this was to introduce the broker config cli. However, to do this, a number of supporting and related changes needed to be made.

The first of these is the new ConfigManager class that manages reading from and writing to the config file.
Since so much logic was implemented for this, it made more sense to roll in the import/init functionality, that was originally in the settings module, into the new class.

This also gave me the opportunity to separate the test config from the example config. This removal, and other changes in this were supported by ConfigManager's migration functionality.

To simplify the nested chunk notation, I moved provider instances out from a list to just being a nested dictionary. This actually simplified the instance logic quite a bit.

Related to config simlification was the separation of the host settings to a new ssh chunk of the config. This is because not all users use the host functionality Broker provides. A likely change with this release is going to be removing a default ssh backend from Broker's requirements.

While I was at it, I also switched the CLI over to rich-click as part of a larger effort to improve the CLI experience.

2024-09-17 20:03 UTC, JacobCallahan commented on broker/config_manager.py
> +        logger.debug(
I'm debating whether this should be info level or not. There is a stronger case for this being info level than the message in backup.

2024-09-17 20:07 UTC, JacobCallahan commented on broker/config_manager.py
> +            # curr = int(curr) if curr.isdigit() else curr
This is a remnant from when I allowed traversing lists, like how instances are currently stored. Could keep it in for some future use or just get rid of these lines.

2024-09-17 20:12 UTC, JacobCallahan commented on broker/config_manager.py
> +    def migrate(self):
i've considered whether we should allow people to force migrations for a target version.

2024-09-17 20:53 UTC, JacobCallahan commented on broker/hosts.py
> +            SETTINGS_VALIDATED = True
delay validation until needed to avoid requiring the ssh config chunk.
this isn't currently important since every setting under ssh has a default value defined in its validator.

2024-09-17 20:54 UTC, JacobCallahan commented on broker/hosts.py
> +        from broker.session import Session
delay import so we can potentially remove the requirement to have a ssh backend installed.

2024-09-17 20:57 UTC, JacobCallahan commented on broker/settings.py
> +            cfg_manager.migrate()
right now this is a choice, but we could also just remove the choice and make it automatic.

2024-09-24 22:52 UTC, JacobCallahan commented
@tpapaioa @ogajduse I'd like to have this merged this week; any thoughts?

2024-09-27 14:49 UTC, JacobCallahan commented on broker/config_manager.py
> +    def migrate(self):
we can now force

2024-09-27 15:20 UTC, ogajduse reviewed
This is a partial review, I went through a quarter of the patch and left some comments.

2024-09-27 15:57 UTC, tpapaioa approved these changes

2024-09-27 16:06 UTC, JacobCallahan commented on broker/commands.py
> +        console.print(table)
good catch!

2024-09-27 17:38 UTC, JacobCallahan commented on broker/config_manager.py
> +        return self._interactive_mode
`sys.flags.interactive` is more for when python is ran with `-i`, so I don't want to go with that. However, I never thought about using `sys.stdin.isatty()` and that's a great suggestion. So I'm going to replace the post-github check with that.

2024-09-27 17:46 UTC, JacobCallahan commented on broker/config_manager.py
> +                self._interactive_mode = False
it will likely never get hit, but just in case....

2024-09-27 23:12 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +YAML().register_class(awxkit.utils.PseudoNamespace)
Actually, it's probably better to act on `helpers.yaml` here
```suggestion
helpers.yaml.register_class(awxkit.utils.PseudoNamespace)
```

2024-09-30 12:40 UTC, ogajduse commented on broker/providers/ansible_tower.py
> +# yaml.add_representer(awxkit.utils.PseudoNamespace, awxkit_representer)
Can this chunk be deleted? We can restore it anytime from a specific git ref.

2024-09-30 12:40 UTC, ogajduse commented on broker/settings.py
> +TEST_MODE = "pytest" in sys.modules
Did you test that `pytest` is not in `sys.modules` when broker is imported in robottelo or a similar project?

2024-09-30 12:40 UTC, ogajduse commented on tests/test_config_manager.py
> +yaml = YAML()
As you suggested in another module, this could be changed to `from broker.helpers import yaml`.

2024-09-30 12:40 UTC, ogajduse commented on broker/config_manager.py
> +                    self._interactive_mode = True
Doesn't `sys.stdin.isatty()` return False if it is being run from GH Actions?
```suggestion
            # determine if we're being run from a CLI
            if sys.stdin.isatty():
                self._interactive_mode = True
```

2024-09-30 12:40 UTC, ogajduse commented on broker/config_manager.py
> +        return self._interactive_mode
I have created a new thread on the same topic. Let's discuss it there.

2024-09-30 15:15 UTC, JacobCallahan commented on broker/config_manager.py
> +        chunk = chunk.split(".")[0] if "." in chunk else chunk
good catch!

2024-09-30 15:16 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +# yaml.add_representer(awxkit.utils.PseudoNamespace, awxkit_representer)
yep, definitely should have been

2024-09-30 15:47 UTC, JacobCallahan commented on broker/settings.py
> +TEST_MODE = "pytest" in sys.modules
it almost certainly should trigger test mode, so we wouldn't automatically migrate while in a pytest session.

2024-09-30 15:50 UTC, JacobCallahan commented on tests/test_config_manager.py
> +yaml = YAML()
for this, we don't need to modify the shared yaml object, so using it directly here to load is fine.

2024-09-30 15:52 UTC, JacobCallahan commented on broker/config_manager.py
> +                    self._interactive_mode = True
unsure, but could test it by adding this to the workflow temporarily
```
python -c "import sys; print(f'{sys.stdin.isatty()=}')"
```

2024-09-30 15:59 UTC, JacobCallahan commented on broker/config_manager.py
> +                    self._interactive_mode = True
update: it is indeed false, based on that test.
```
sys.stdin.isatty()=False
```

2024-09-30 16:05 UTC, JacobCallahan commented on broker/config_manager.py
> +                    self._interactive_mode = True
and now completely removed that property in favor of a class attribute, thanks!

2024-10-01 09:46 UTC, ogajduse commented on broker/settings.py
> +TEST_MODE = "pytest" in sys.modules
Let me rephrase, do we want to have `TEST_MODE` set to `True` when we run robottelo (Foreman) tests? If we don't, this logic needs to be changed.
`pytest --setup-plan tests/foreman/api/test_ping.py -s`
```python
[74] > /home/ogajduse/repos/broker/broker/settings.py(28)<module>()
-> TEST_MODE = "pytest" in sys.modules
   2 frames hidden (try 'help hidden_frames')
(Pdb++) l
 23  	from broker.exceptions import ConfigurationError
 24  	
 25  	INTERACTIVE_MODE = ConfigManager.interactive_mode
 26  	BROKER_DIRECTORY = Path.home().joinpath(".broker")
 27  	breakpoint()
 28  ->	TEST_MODE = "pytest" in sys.modules
 29  	
 30  	if TEST_MODE:  # when in test mode, don't use the real broker directory
 31  	    BROKER_DIRECTORY = Path("tests/data/")
 32  	elif "BROKER_DIRECTORY" in os.environ:
 33  	    envar_location = Path(os.environ["BROKER_DIRECTORY"])
(Pdb++) "pytest" in sys.modules
True
```

2024-10-01 16:19 UTC, tpapaioa requested changes

2024-10-01 16:19 UTC, tpapaioa commented on broker/session.py
> +SSH_BACKEND = settings.BACKEND
```suggestion
SSH_BACKEND = settings.SSH.BACKEND
```

2024-10-01 17:52 UTC, JacobCallahan commented on broker/session.py
> +SSH_BACKEND = settings.BACKEND
fixed

2024-10-01 20:44 UTC, ogajduse approved these changes

2024-10-03 14:18 UTC, merged