Rework inventory cli
SatelliteQE/broker pull request #324
Opened 2024-10-07 20:36 UTC by JacobCallahan

With the changes we've been making in 0.6 toward a better, more customizable and visually appealing, user experience. It's time that we revisited the inventory command.
The --curated view introduced in 0.5.x has now become the default inventory view. The original default view is now present in its new form and home with the --list flag.
The --details flag largely retains the functionality it did before. However, it involves much less processing than before.

One important piece added in this is the ability to customize the inventory fields on a per-user basis. The details on this customization are documented in detail in the supporting code.
It will also be important to document this in the wiki upon release.

Here's a screenshot of what the new changes look like (with the details view cut-off for security).
![Screenshot from 2024-10-07 16-26-56](https://github.com/user-attachments/assets/93677c13-c622-4070-b26f-50ea8b6b6565)

2024-10-07 20:59 UTC, JacobCallahan commented on broker/commands.py
> +        {"Host": "hostname | name | ip"} if _list else settings.settings.inventory_fields
The list fields are hard coded here, but we could also make them configurable..

2024-10-08 01:46 UTC, JacobCallahan commented on broker/config_migrations/v0_6_0.py
> +def add_inventory_fields(config_dict):
Need to add this to the call chain below.

2024-10-08 01:46 UTC, JacobCallahan commented on broker/commands.py
>      """Get a list of all hosts you've checked out showing hostname and local id.
Update the description here

2024-10-08 01:46 UTC, JacobCallahan commented on broker_settings.yaml.example
> +inventory_fields:
Should likely add a validator for this

2024-10-08 13:38 UTC, JacobCallahan commented
@ogajduse enjoy.... lol
The color in there is likely just from how my terminal is setup to handle bolded text.
![Screenshot from 2024-10-08 09-33-49](https://github.com/user-attachments/assets/00d15d6a-a4d8-45ac-ba3d-c07708ea91db)

2024-10-10 20:24 UTC, tpapaioa requested changes

2024-10-10 20:43 UTC, tpapaioa approved these changes

2024-10-10 22:34 UTC, merged