Use concurrent.futures work fix multiprocessing issues
SatelliteQE/broker pull request #53
Opened 2020-09-22 00:13 UTC by jaryn

Test

2020-09-24 14:28 UTC, JacobCallahan commented on broker/providers/test_provider.py
> +        host_type.connect = MagicMock()
have you considered using the MockStub class from helpers here?

2020-09-24 16:26 UTC, jaryn commented on broker/providers/test_provider.py
> +        host_type.connect = MagicMock()
It is actually not needed to mock something here. The connect got called due to a bug in my PR which I have fixed now.

I like to use MagicMock though. It is in standard library, quite well documented and thus it is likely the other developers will know how to use it. I did use it to make the code raise an exception in `broker._act` in other tests.

2020-09-24 17:52 UTC, jaryn commented on .travis.yml
> +install: pip install .[test]
I am not sure this is the best way to install the test deps. Perhaps we should just use tox.

2020-09-24 18:00 UTC, jaryn commented on broker/broker.py
> +    MAX_WORKERS = 5
I need to discuss this. I think the count of workers should be independent from the number of the machines to check out.

I also think the number of machines to check out should not be an attribute of the broker.

2020-09-24 19:20 UTC, JacobCallahan commented on broker/broker.py
> +    MAX_WORKERS = 5
What benefit would there be to decoupling the number of workers from the number of vms?

It is an attribute of broker, as (almost) all broker arguments are. This is a design choice to make broker as flexible as possible.

2020-09-24 19:25 UTC, JacobCallahan commented on .travis.yml
> +install: pip install .[test]
what test deps?

2020-09-24 19:27 UTC, JacobCallahan requested changes

2020-09-24 19:27 UTC, JacobCallahan commented on broker/broker.py
> +    def __init__(self, func: callable = None):
no type annotations

2020-09-24 20:47 UTC, jaryn commented on .travis.yml
> +install: pip install .[test]
https://github.com/SatelliteQE/broker/pull/53/files#diff-2eeaed663bd0d25b7e608891384b7298R12

2020-09-24 20:47 UTC, jaryn commented on broker/broker.py
> +    MAX_WORKERS = 5
If we are talking about dealing with counts of VMs in ballpark figures like 20 at most then I guess we don't need to limit the workers count (it can be set to the count of the objects). We can add the limit in future if there was a need for this.

I don't understand the design choice and how it is making the broker more flexible. I don't mean this is not right, but I just don't understand.

2020-09-25 19:07 UTC, JacobCallahan commented on broker/broker.py
> +    MAX_WORKERS = 5
we can have a larger discussion about how broker is designed via gchat

2020-09-25 19:30 UTC, JacobCallahan requested changes

2020-09-25 19:30 UTC, JacobCallahan commented on broker/broker.py
> -                self._hosts.append(host)
why are you removing this?

2020-09-25 19:30 UTC, JacobCallahan commented on broker/broker.py
> +    def _checkout(self, connect=False):
what is the purpose of making this a private method, then moving existing functionality from this to the new public method?

2020-09-25 19:30 UTC, JacobCallahan commented on broker/providers/test_provider.py
> +        host_inst = host_type(**host_params)
why separate these two lines?

2020-09-25 19:30 UTC, JacobCallahan commented on tests/test_broker.py
> +def test_mp_checkout_exc(mocker):
what is the value of this test? _act is already hit multiple times in previous tests.

2020-09-25 20:27 UTC, jaryn commented on broker/broker.py
> +    def _checkout(self, connect=False):
the problem is that I found cumbersome the fact that it sometimes returned a list and sometimes a host. This is inconvenient for the caller (the generalized mp_decorator).

2020-09-25 20:39 UTC, jaryn commented on broker/broker.py
> -                self._hosts.append(host)
Because the `self._hosts` either has to be
 * a state shared between the processes -- and we need a Manager https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes chech the Server processes there)
 * or has to be accessed only in the parent. I think our case is perfect example when we don't need any shared state like this and we can just collect the results in the parent process.

The self._hosts is filled on https://github.com/SatelliteQE/broker/pull/53/files#diff-03b5bdba9f4a407652b7f9778cddb939R120 which is the result of the mp_split decorator 
https://github.com/SatelliteQE/broker/pull/53/files#diff-03b5bdba9f4a407652b7f9778cddb939R45

2020-09-25 20:40 UTC, jaryn commented on broker/providers/test_provider.py
> +        host_inst = host_type(**host_params)
This is just a leftover. I can make it look as before if it matters.

2020-09-25 21:25 UTC, jaryn commented on tests/test_broker.py
> +def test_mp_checkout_exc(mocker):
Well it is a test for situations like in https://github.com/SatelliteQE/broker/issues/44. There I only made fixes in the product so the `test_mp_checkout` passes in normal situations.

The `test_mp_checkout_exc` is though is a negative test (I hate that term) -- designed to raise exception (`act.side_effect = SoemeException()`) in the the child and checking the system behaves well on failure.
 * it checks whether the exception is propagated to the parent process
 * If there is a deadlock, well we should see it.

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.side_effect

2020-09-25 22:09 UTC, jaryn commented on tests/test_broker.py
> +def test_mp_checkout_exc(mocker):
done

2020-10-01 17:58 UTC, JacobCallahan requested changes
some small changes

2020-10-01 17:58 UTC, JacobCallahan commented on broker/broker.py
> +            max_workers_count = count if self.MAX_WORKERS is None else self.MAX_WORKERS
```suggestion
            max_workers_count = self.MAX_WORKERS or count
```

2020-10-01 17:58 UTC, JacobCallahan commented on broker/broker.py
> +     If set to None, the max workers count of the EXECUTOR will be matching the count of items."""
```suggestion
     If set to None, the max workers count of the EXECUTOR will match the count of items."""
```

2020-10-02 18:29 UTC, JacobCallahan approved these changes
ACK

2020-10-02 18:30 UTC, JacobCallahan commented
@mshriver do you want to weigh in as well?

2020-10-05 13:23 UTC, mshriver commented on .travis.yml
> +install: pip install .[test]
I would agree with this approach, doing the same thing in a wt.core PR at the moment.

2020-10-05 13:30 UTC, mshriver commented on broker/broker.py
> +                for f in completed_futures:
Might be code golfing here, but couldn't you directly return here instead?

```
return [f.result() for f in completed_futures]
```

2020-10-05 14:52 UTC, mshriver commented on broker/broker.py
> +            logger.debug(f"{host=} {connect=}")
I'm hitting an f-string exception on this line when I try to run your branch locally.  I'm not aware of any f-string usage for `<var>=` syntax, what was your intent here?

2020-10-05 15:06 UTC, mshriver commented on broker/broker.py
> +            logger.debug(f"{host=} {connect=}")
Discussed - its an f-string feature introduced in 3.8, but we have a need to support 3.6+ so it needs to be updated here.

2020-10-05 15:57 UTC, jaryn commented
There are some problems with the inventory.yaml unlink when doing multiple checkouts. I recommend not merging before I it is known why this happens.

2020-10-06 18:00 UTC, jaryn commented
I think the problem with race condition between the children of single process is fixed by this PR. We are ready to merge @mshriver @JacobCallahan

2020-10-12 13:42 UTC, merged