Clenups
SatelliteQE/broker pull request #62
Opened 2020-09-29 15:02 UTC by jaryn

2021-01-21 18:58 UTC, swadeley commented on broker/broker.py
>          :return: Any The results given back by the provider
```suggestion
        :return: Any results given back by the provider
```

2021-07-26 15:09 UTC, JacobCallahan requested changes

2021-07-26 15:09 UTC, JacobCallahan commented on broker/providers/__init__.py
> +        )
This shouldn't have any reference to a child provider, in this case TestProvider. 

To make this flexible, you could switch it so `_broker_provider` is set to `self.__class__.__name__`

2021-07-26 15:09 UTC, JacobCallahan commented on broker/providers/__init__.py
> +from abc import ABC, abstractmethod
were you planning on using these?

2021-07-26 15:09 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +        super().__init__()
ehhhh... I'm not sure if the calls are worth it at this point.

2021-07-26 15:09 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> -
In this PR's current state, the _broker_provider would become TestProvider

2021-07-26 15:09 UTC, JacobCallahan commented on broker/providers/test_provider.py
> +        return super().construct_host(provider_params, host_classes, **kwargs)
with this PR, you wouldn't need to define `construct_host` here

2023-03-31 01:01 UTC, closed without merging