Add tox
SatelliteQE/broker pull request #64
Opened 2020-10-05 15:44 UTC by jaryn

This adds support for tox for making testing multiple configuraitons easier.

Some tests seem to be failing under tox though. This seems to be due to race condition.

Can we require use of pbr package?

2020-10-05 19:00 UTC, mshriver commented
Not to burst any bubbles, but I'd like to keep broker off of tox.

I think we can target python 3.8 for CI, adding new versions as we want to test them in CI.

I like your approach of adding an extras_require for pip install with `[test]` to get the dependencies for testing locally.

Are you open to changing your focus/approach here to moving us to github workflows for running pre-commit/pytest, instead of using travis?

2020-10-05 19:20 UTC, jaryn commented
> Not to burst any bubbles, but I'd like to keep broker off of tox.
Not sure why, but I am not insisting on using tox. I just found it useful to be able to run the tests locally.
> 
> I think we can target python 3.8 for CI, adding new versions as we want to test them in CI.
> 
> I like your approach of adding an extras_require for pip install with `[test]` to get the dependencies for testing locally.
OK. I think it is included in this PR. But probably should.
> 
> Are you open to changing your focus/approach here to moving us to github workflows for running pre-commit/pytest, instead of using travis?

I did add github workflows as well as I've changed the travis.yaml. They are now both passing (The github actions on my personal repo and the Sattelite travis).

2020-10-06 19:48 UTC, mshriver commented on .github/workflows/python-package.yml
> +  build:
Can you give this a bit more descriptive/pretty name, since its not really building, but running pytest?

2020-10-06 19:49 UTC, mshriver commented on .github/workflows/python-package.yml
> +        python -m pip install --upgrade pip
With the setup-python action you shouldn't really have to worry about upgrading pip.

I think it would be best to have a 'test' extra_requires for setuptools, and then just `pip install -e .[test]` here, instead of looking for requirements files.

2020-10-06 19:50 UTC, mshriver commented on tox.ini
> +[tox]
Please remove tox and just use pytest directly within the github workflow. Matrix for the workflow should take care of running against multiple versions of python.

2020-10-06 19:51 UTC, mshriver commented on .travis.yml
> +    - "3.6"
We're not concerned about testing versions earlier than 3.8, but since 3.9 just released it would be great to include that.

2020-10-09 14:21 UTC, jaryn commented on .github/workflows/python-package.yml
> +  build:
I will try. I have used pre-existing scaffold that seemed to do what we want.

2020-10-09 14:29 UTC, jaryn commented on .github/workflows/python-package.yml
> +        python -m pip install --upgrade pip
Upgrading pip was part of the scaffold. Not sure is it safer to upgrade or not-upgrade it every time, but I am certain it is not necessary. I will remove that.

> I think it would be best to have a 'test' extra_requires for setuptools, and then just pip install -e .[test] here, instead of looking for requirements files.

I think you mean to have setuptools among the the extra_requires. OK, will do.

How are the setuptools related to requirements file I don't know, but the file is not present and IIUC we don't need it unless we are composing an reproducible environment of mulitiple packaged projects.

2020-10-09 14:38 UTC, jaryn commented on .travis.yml
> +    - "3.6"
https://github.com/SatelliteQE/broker/pull/53#discussion_r499669068 tells we need support 3.6+.  So according to that I am not sure if 3.6, but I am certain it means 3.7 is meant to be supported and therefore the removing the f-string debug was justified.

Are we or are we not concerned about <3.8 and thus can I use f-string debugs?

2020-10-09 14:40 UTC, jaryn commented on tox.ini
> +[tox]
not when running locally, but ok

2020-10-12 11:25 UTC, mshriver commented on .github/workflows/python-publish.yml
> +    - name: Build and publish
I think we should use pypa's action for this:
https://github.com/pypa/gh-action-pypi-publish

2020-11-12 20:18 UTC, mshriver reviewed
I'd support this move to github actions.

Concerning use of install_requires / pbr+requirements.txt, I would leave it as is with install_requires and loose versions where possible.

2021-06-25 15:23 UTC, JacobCallahan requested changes

2021-06-25 15:23 UTC, JacobCallahan commented on .github/workflows/python-package.yml
> +        python-version: [3.7, 3.8]
3.8 and 3.9

2021-07-01 17:51 UTC, mshriver commented
I've taken these commits and made some further updates, not including tox anymore:
https://github.com/SatelliteQE/broker/pull/116

2021-07-09 13:59 UTC, closed without merging