Add the ability for broker to process ansible tower inventories
SatelliteQE/broker pull request #95
Opened 2021-03-26 20:27 UTC by JacobCallahan

Broker can now accept ansible tower inventories both via cli and config.
We now have a new exception handling system as well as a way to
gracefully handle kyboardinterrupts.
Providers can now specify checkout and execute cli arguments in their
class definition.
Minor refactor and improvements.

2021-03-29 15:50 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +        if (new_inv := broker_args.get("tower_inventory", broker_args.get("inventory"))) :
the specific names here will be dependent on what the SatLab team decided to return in set_stats output.
@bherrin3

2021-03-30 17:22 UTC, JacobCallahan commented on broker/__init__.py
> +from broker.broker import VMBroker
Here's a bonus for everyone :)
Enables this:
```python
from broker import VMBroker
```

2021-04-02 18:56 UTC, JacobCallahan commented
@mshriver I decided to beef up Broker's testing ability while this pr was waiting. There are now a series of functional tests added with users being able to add their own custom test scenarios!
This would also make genealogist integration much easier!
@kedark3 trying to make your dream come true :)

2021-04-05 14:38 UTC, kedark3 commented
@JacobCallahan I have faith in you and @bherrin3 for pushing some of the things with Tower :)

2021-04-05 14:46 UTC, bherrin3 commented on tests/cli_scenarios/test_satlab.py
> +from pathlib import Path
Just noting that a significant discussion has happened here for this `test` section between @JacobCallahan and I. 

While the main purpose of this PR is AT Inventories, this is a significant Phase 0 effort for testing against tower and tower infrastructure.

This should be a genesis for future conversation about the possibilities here. 

Thanks for including the start for this capability.

2021-04-08 14:25 UTC, mshriver commented on HISTORY.md
> +0.1.11 (2021-03-26)
Seems like a significant enough change set for `0.2`

2021-04-08 14:40 UTC, mshriver commented on broker/providers/__init__.py
> +        try:
:+1:

2021-04-08 14:46 UTC, mshriver commented on broker/providers/ansible_tower.py
> +        provider="AnsibleTower", message="Unable to import awxkit. Is it installed?"
"u dumb bro?"

2021-04-08 14:48 UTC, mshriver commented on broker/providers/ansible_tower.py
> +            except awxkit.exceptions.Unauthorized as err:
:+1:

2021-04-08 14:51 UTC, mshriver commented on broker/providers/ansible_tower.py
> +            self._resolve_inventory_id()
I'm a bit concerned about the pattern here of having to call _resolve_inventory_id() before any workflows/JTs are called on tower.

Would it be better to use a class property for the inventory ID that has been resolved, and a 'private' `self._inventory` to set the inventory name from config/args?

That way the inventory ID would be automatically resolved when necessary - the property could even be cached so that we don't resolve it more than once for an instance of the tower provider.

2021-04-08 14:57 UTC, mshriver commented on broker/providers/ansible_tower.py
> +                job, strategy=kwargs.get("strategy", "last")
:clap: @bherrin3 will be happy to see this changing.

2021-04-08 15:00 UTC, mshriver commented on broker/providers/ansible_tower.py
> +            if user in inv.name or user == "@ll"
SNEAKY

2021-04-08 15:10 UTC, mshriver commented on broker/providers/ansible_tower.py
> +        elif (inventory := kwargs.get("inventory")) :
extra space before the colon

2021-04-08 15:11 UTC, mshriver commented on inventory.yaml.bak
> +[]
I'm guessing you didn't want to include this file, given its `.bak` extension

2021-04-08 15:13 UTC, mshriver requested changes
One outstanding discussion about the pattern concerning `_resolve_inventory_id`, otherwise looking great!

2021-04-08 15:29 UTC, JacobCallahan commented on HISTORY.md
> +0.1.11 (2021-03-26)
not yet :)
I have plans for 0.2!

2021-04-08 15:30 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +            self._resolve_inventory_id()
Good point! I'll change this to a cached property

2021-04-08 15:31 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +                job, strategy=kwargs.get("strategy", "last")
i think it has become the standard now

2021-04-08 15:31 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +            if user in inv.name or user == "@ll"
shhhhhh

2021-04-08 15:32 UTC, JacobCallahan commented on broker/providers/ansible_tower.py
> +        elif (inventory := kwargs.get("inventory")) :
yeah i'm not sure why, but black prefers it with the space for some reason...

2021-04-08 15:33 UTC, JacobCallahan commented on inventory.yaml.bak
> +[]
ahhh good catch! something to add to the ignore. should normally be cleaned up by properly exited tests

2021-04-08 19:22 UTC, mshriver approved these changes

2021-04-09 13:04 UTC, rdrazny commented
Doing a deploy with an inventory explicitly set works (do not mind the `broker-cmd` name, I use it so I don't have to do complete broker install into virtenv), but I get the following error at the end:
```
broker ❯ ./broker-cmd checkout --nick rhel7 --tower-inventory satlab-osp-01-inventory --AnsibleTower osp-deploy-fix-rd
[INFO 210331 14:01:54] Using provider AnsibleTower to checkout
[INFO 210331 14:01:54] Using username and password authentication
[INFO 210331 14:01:58] Waiting for job: 
    API: https://dhcp-2-172.vms.sat.rdu2.redhat.com/api/v2/workflow_jobs/137/
    UI: https://dhcp-2-172.vms.sat.rdu2.redhat.com/#/workflows/137
[INFO 210331 14:12:49] Host: ci-vm-10-0-103-113.hosted.upshift.rdu2.redhat.com
[ERROR 210331 14:12:49] BrokerError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:awxkit.utils.PseudoNamespace'
      in "inventory.yaml", line 10, column 23
```
The `inventory.yml` looks like this:
```
- _broker_args:
    AnsibleTower: osp-deploy-fix
    deploy_rhel_version: '7.9'
    fqdn: ci-vm-10-0-101-146.hosted.upshift.rdu2.redhat.com
    host_type: host
    name: satlab_admin_test-rhel-7.9-server-x86_64-released-1617190794
    notes: Requested by broker
    os_distribution: RedHat
    os_distribution_version: '7.9'
    reported_devices: !!python/object/new:awxkit.utils.PseudoNamespace
      dictitems:
        nics:
        - lo
        - eth0
    rhel_version: '7.9'
    template: rhel-7.9-server-x86_64-released
    tower_inventory: satlab-osp-01-inventory
    workflow: deploy-base-rhel
  _broker_provider: AnsibleTower
  hostname: ci-vm-10-0-101-146.hosted.upshift.rdu2.redhat.com
  name: satlab_admin_test-rhel-7.9-server-x86_64-released-1617190794
  type: host
```

2021-04-09 18:56 UTC, JacobCallahan commented
@rdrazny that is expected because of the nested reported_devices data structure in set_stats.
 In order to solve this, we'd either need to submit a change to awxkit or write a custom yaml dumper class.

2021-04-12 14:15 UTC, merged